# Generated by Django 5.1.5 on 2025-01-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider', verbose_name='Slider image')),
                ('title', models.CharField(max_length=60, verbose_name='Slider title')),
                ('text', models.TextField(verbose_name='Slider text')),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
