# Generated by Django 5.1.5 on 2025-01-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
                ('image', models.ImageField(upload_to='about', verbose_name='About image')),
            ],
        ),
    ]
