# Generated by Django 5.1.5 on 2025-01-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='button_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
