# Generated by Django 5.1.5 on 2025-01-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('fb', models.TextField()),
                ('ins', models.TextField()),
                ('X', models.TextField()),
            ],
        ),
    ]
