# Generated by Django 5.1.5 on 2025-01-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='X',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='fb',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='ins',
            field=models.URLField(),
        ),
    ]
